config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, except: :create
  devise_for :users

  namespace :admin do
    resources :products

    root to: "admin#dashboard"
  end

  resources :products

  root to: "products#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
# frozen_string_literal: true

class Brand < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand

  validates :name, presence: true
  validates :price, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1 }
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin/admin_controller.rb
# frozen_string_literal: true

class Admin::AdminController < ApplicationController
  before_action :user_admin_authenticate

  def user_admin_authenticate
    unless current_user.admin?
      flash[:alert] = 'You are not authorized'
      redirect_to root_path
    end
  end

  def dashboard
    @categories = Category.all
    @brands = Brand.all
    @search = Product.ransack(params[:q])
    @products = @search.result.joins(:category, :brand)
  end

  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_root_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admin_root_path, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_root_path, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image, :category_id, :brand_id)
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @categories = Category.all
    @brands = Brand.all
    @search = Product.ransack(params[:q])
    @products = @search.result.joins(:category, :brand)
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to product_path, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image, :category_id, :brand_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end

  private

  def unauthorized
    redirect_to root_path, flash: 'You are not authorized'
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @categories = Category.all
    @brands = Brand.all
    @search = Product.ransack(params[:q])
    @products = @search.result.joins(:category, :brand)
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to product_path, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image, :category_id, :brand_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_flash_class(type)
    case type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/admin/admin/dashboard.html.erb
<h3>Admin Panel</h3>

<h1>Products</h1>



<div class="row">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th colspan="3"></th>
        <th>Category</th>
        <th>Brand</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= product.category.name %></td>
          <td><%= product.brand.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>Admin Panel</h1>

<h2>New Product</h2>
  <%= form_for [:admin, @product] do |f| %>
    <div class="col-6">
      <%= f.file_field :cover_photo  %>
    </div>
    <br>

    <div class="col-6">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col-6">
      <%= f.label :price, class: "form-label"  %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="col-6">
      <%= f.label :category, class: "form-label"  %>
      <%= f.collection_select(:category_id, Category.all, :id, :name,
      { prompt: "Select" }) %>
    </div>

    <div class="col-6">
      <%= f.label :brand, class: "form-label"  %>
      <%= f.collection_select(:brand_id, Brand.all, :id, :name,
      { prompt: "Select" }) %>
    </div>
    <%= f.submit %>
  <% end %>

app/views/application/_flash_messages.html.erb
<% if flash.any? %>
  <div class="container">
    <div class="row">
      <div class="col">
        <% flash.each do |type, msg| %>
          <div class="alert <%= bootstrap_flash_class(type) %> alert-dismissable fade show">
            <%= msg %>
            <button class="close" data-dismiss="alert">x</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <a class="navbar-brand" href="/">Ruby Lovers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <span class="navbar-text"> <%= current_user.email %> </span>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary btn-inverse'%>
        <% else %>
          <%= link_to "Sign in", new_user_registration_path, class: 'nav-link btn btn-outline-secondary btn-inverse'%> 
          <%= link_to "Log in", new_user_session_path, class: 'nav-link btn btn-outline-secondary btn-inverse'%>
        <% end %>
        <%= link_to "Admin Panel", admin_root_path, class: 'nav-link btn btn-outline-secondary btn-inverse'%>      </ul>
    </div>
  </div>
</nav>

app/views/application/_products_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/application/_sidebar.html.erb
<%# <h3 class="my-4">Categories</h4>
<div class="list-group">
  <% @categories.each do |category| %>
    <%# <%= link_to category.name, category %>
  <%# <% end %> 
<%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'navigation' %>
    <%= render 'flash_messages' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= render 'products_carousel' %>

          <%= yield %>
        </div>

        <div class="col-lg-3">
          <%= render 'sidebar' %>
        </div>
      </div>
    </div>
  </body>

  <%= javascript_pack_tag 'application' %>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.collection_select(:category_id, Category.all, :id, :name) %>
    </div>

    <div class="field">
      <%= form.label :brand %>
      <%= form.collection_select(:brand_id, Brand.all, :id, :name) %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= search_form_for @search, url: products_path do |f| %>
  <div class="field">
    <%= f.label :name_cont, "Name" %>
    <%= f.text_field :name_cont %>
  </div>

  <h5>Categories:</h5>
  <% @categories.each do |category| %>
    <%= f.check_box :category_id_in, {multiple: true}, category.id, nil %>
    <%= category.name %>
  <% end %>

  <h5>Brands:</h5>
  <% @brands.each do |brand| %>
    <%= f.radio_button :brand_id_in, brand.id, {multiple: true} %>
    <%= brand.name %>
  <% end %>

  <%= f.submit "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
      <th>Category</th>
      <th>Brand</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= product.category.name %></td>
        <td><%= product.brand.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>